# Generated by Django 4.2.3 on 2023-07-28 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maydon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmodel',
            name='bron_date',
        ),
        migrations.CreateModel(
            name='BronModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bron_date', models.DateField(verbose_name=datetime.datetime.now)),
                ('bron_time', models.CharField(choices=[('9:00-10:00', '9:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('18:00-19:00', '18:00-19:00'), ('20:00-21:00', '20:00-21:00'), ('22:00-23:00', '22:00-23:00')])),
                ('field_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maydon.fieldmodel')),
            ],
        ),
    ]
