# Generated by Django 4.2.3 on 2023-07-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usermodel'),
        ('maydon', '0002_remove_fieldmodel_bron_date_bronmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronmodel',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.usermodel'),
        ),
    ]
