# Generated by Django 4.2.3 on 2023-07-28 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maydon', '0003_bronmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronmodel',
            name='bron_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 28, 5, 11, 7, 680924)),
        ),
    ]
