# Generated by Django 4.2.3 on 2023-07-28 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maydon', '0004_alter_bronmodel_bron_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='bronmodel',
            name='bron_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 7, 28, 5, 12, 45, 848322)),
        ),
    ]
